name: Mirror repo data to Google Drive

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  mirror-to-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload data folder (mirror structure)
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          filename: data
          overwrite: "true"
          mirrorDirectoryStructure: "true"

      - name: Upload builds folder (mirror structure)
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          filename: builds
          overwrite: "true"
          mirrorDirectoryStructure: "true"
